codegen:
  swagger:
    title: "Title for swagger codegen"
    description: |
      # Description can be input as markdown
    servers:
      - url: https://example.com/api
        description: example site

      - url: https://demo.com/api
        description: demo site