[package]
name = "tot_spec_util"
version = "0.1.0"
edition = "2021"
description = "Util crate for tot_spec codegen"
license = "MIT OR Apache-2.0"
categories = ["codegen"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ibig = "0.3"

[dev-dependencies]
serde_json = "1.0"